using System;
using System.IO;
using System.Linq;
using System.Reflection;
using FluentNHibernate.Cfg;
using Infrastructure.ApplicationSettings;
using NHibernate;
using NHibernate.Tool.hbm2ddl;
using Configuration = NHibernate.Cfg.Configuration;


namespace Data.Utils
{
	public class NHibernateHelper
	{
		public static ISessionFactory SessionFactory;
		private static readonly Configuration Configuration;

        /// <summary>
		///     Constructor
		/// </summary>
		/// <remarks>
		///     Static contructors are called automatically before the first instance is created or any static members are referenced.
		///     A static constructor is executed only once.
		/// </remarks>
		static NHibernateHelper()
		{
            var applicationSettings = new ApplicationSettings();
            
            // Build NHibernate session factory, expensive proces, should only fire when application first starts
			// Configuration is set in .config file
			Configuration = new Configuration();
			Configuration.SetProperty(NHibernate.Cfg.Environment.ConnectionString, applicationSettings.ConnectionString);
			Configuration.Configure();
			
			SessionFactory = Fluently.Configure(Configuration)
				.Mappings(m =>
				  m.FluentMappings.AddFromAssembly(Assembly.GetExecutingAssembly()))
                //.Mappings(m=>m.FluentMappings.ExportTo("c:\\temp"))
				.BuildSessionFactory();
		}

		/// <summary>
		///     Creates database schema based on mappings
		/// </summary>
		public static void CreateDatabaseSchema()
		{
			var schemaExport = new SchemaExport(Configuration);
			schemaExport.Drop(false, true);
			schemaExport.Create(false, true);

			// Excute custom sql which is not generated by NHibernate
			ExecuteCustomSql();
		}

		/// <summary>
		///     Executes custom sql statements to complete the creation of the database schema
		/// </summary>
		/// <remarks>
		///     NHibernate's schemaexport only create tables and fields which are mapped to entities.
		///     Other fields (e.g. password field) must be created using custom sql.
		///     All files included in 'CustomSql' directory are processed in alphabetical order.
		///     Make sure files are marked as embedded resources!
		/// </remarks>
		private static void ExecuteCustomSql()
		{
			// Get reference to this assembly
			var assembly = Assembly.GetExecutingAssembly();

			// List of custom sql files
			var sqlFiles = assembly.GetManifestResourceNames().Where(x => x.Contains("CustomSql"));

			// Create database connection
			using (var connection = SessionFactory.OpenSession().Connection)
			{
				// Process files
				foreach (var sqlFile in sqlFiles.OrderBy(x => x))
				{
					// Get resource
					var sqlStream = assembly.GetManifestResourceStream(sqlFile);

					// Create sql command
					var command = connection.CreateCommand();

					var splitter = new[] {"GO"};
					if (sqlStream != null)
					{
						var commandTexts = new StreamReader(sqlStream)
                            .ReadToEnd()
                            .Split(splitter,StringSplitOptions.RemoveEmptyEntries);

						foreach (var commandText in commandTexts)
						{
							command.CommandText = commandText;

							// Execute sql
							command.ExecuteNonQuery();
						}
					}					
				}
			}
		}
    }
}